### ISSUE TITLE
Linking in android misses main gradle.build insert

### ISSUE THREAD

**Issue by TitanKing** [transistorsoft/react-native-background-geolocation-firebase#1]
The following insert is missing from main `build.gradle` when linking with `react-native link react-native-background-geolocation-firebase`;

```
        maven {
            url "$rootDir/../node_modules/react-native-background-geolocation-firebase/android/libs"
        }
```

**Comment by christocracy** [comment]
I don't know how to automate that.  

It's in the [Setup docs](https://github.com/transistorsoft/react-native-background-geolocation-firebase/blob/master/docs/INSTALL-ANDROID-RNPM.md)

you *have to* manually add that.
