### ISSUE TITLE
Question, can this be reconfigured multiple times for changing collections

### ISSUE THREAD

**Issue by SamMatthewsIsACommonName** [transistorsoft/react-native-background-geolocation-firebase#11]
Hi, 
When you specifiy the collection path at the configure stage:

````
  BackgroundGeolocationFirebase.configure({
      locationsCollection: "locations",
      geofencesCollection: "geofences"
    });
````
Can this be reconfigured multiple times? For example out users have locations associated with shifts, and they can clock out of shifts and into others without closing etc. Is it safe to call configure each time to write to a unique collection like:

````
  BackgroundGeolocationFirebase.configure({
      locationsCollection: `locations/${userID}/${thisShiftIDWhichMayChange}`,
      geofencesCollection: "geofences"
    });
````

?
Thanks

**Comment by christocracy** [comment]
Yes

**Comment by SamMatthewsIsACommonName** [comment]
Thanks
