### ISSUE TITLE
GeoFire compatibility

### ISSUE THREAD

**Issue by EskelCz** [transistorsoft/react-native-background-geolocation-firebase#13]
Just a question. I'd like to use GeoFire/GeoFireX (or something similar) to filter locations based on radius. What I gathered from documentations, they use [latitude, longitude] or Firebase GeoPoint type as a format for locations.
I know I can use a Firebase Function to transform each new entry, however those are paid operations. Although pretty inexpensive, it seems like unnecessary overhead, for basically one variable change.

So my question is, would you be willing to provide an interface for this compatibility, or should I rather change the default Schema in a fork? Will your license system still work in that case?

Or if you know of any other system/library that would be a better fit to achieve this functionality, I'd be glad to hear about it.

Thanks for your consideration.

**Comment by christocracy** [comment]
I’d rather not mess with providing configurable Schema.

Use Firebase functions.  They are [incredibly inexpensive](https://cloud.google.com/functions/pricing) since simply massaging the data doesnt involve Network fees and only minute compute time.

For 10M invocations, it’s less than $10.

For <=2M invocations, it’s free.

**Comment by christocracy** [comment]
>Will your license system still work in that case?

Yes.

**Comment by christocracy** [comment]
This is the Firebase Function pricing scenario for simply massaging data:  "Simple Background Function":
![](https://dl.dropboxusercontent.com/s/7t0mzn063vhvy8m/Screenshot%202019-02-14%2009.24.45.png?dl=1)

**Comment by EskelCz** [comment]
Ok, sounds reasonable, thank you
