### ISSUE TITLE
Android gradle dependencies need change

### ISSUE THREAD

**Issue by EskelCz** [transistorsoft/react-native-background-geolocation-firebase#14]
The library is failing to build for android, with this error:

```
Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
```

It needs to be changed in ./android/build.gradle
Thanks

**Comment by christocracy** [comment]
The Firebase adapter will be updated next week, but that’s just a warning, not a build-Failure

**Comment by EskelCz** [comment]
I see, ok, thanks. The actual build error in my case is:
```
Gradle sync failed
Unresolved dependencies
Failed to resolve: com.transistorsoft:tslocationmanager:+
```
(in the same file)
I thought it's related but I'm not sure.

**Comment by christocracy** [comment]
Show me your gradle files:
- `android/build.gradle`
- `android/app/build.gradle`

**Comment by EskelCz** [comment]
Found the problem exactly there and it's building again. Thanks

**Comment by christocracy** [comment]
I've changed `compile` -> `implementation`.  Also updated the default `firebaseCoreVersion`, `firebaseFirestoreVersion`:

Released to `0.2.0`

```diff
buildscript {
    ext {
	googlePlayServicesLocationVersion = "16.0.0"
        buildToolsVersion = "28.0.3"
        minSdkVersion = 16
        compileSdkVersion = 28
        targetSdkVersion = 28
        supportLibVersion = "28.0.0"
+      firebaseCoreVersion = "16.0.9"
+      firebaseFirestoreVersion = "19.0.0"

    }
}

**Comment by williamswebworks** [comment]
@EskelCz What was your fix, I am running into this issue now myself

**Comment by christocracy** [comment]
Post your two gradle files.

**Comment by williamswebworks** [comment]
@christocracy I was able to resolve by adding the following to my build.gradle

allprojects {
    repositories {
        mavenLocal()
        
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
        maven {
            url 'https://maven.google.com/'
            name 'Google'
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }
        maven {
            url "$rootDir/../node_modules/react-native-background-geolocation/android/libs"
        }
        maven {
            url "$rootDir/../node_modules/react-native-background-fetch/android/libs"
        }

**Comment by christocracy** [comment]
@williamswebworks That's exactly as documented in the *Android Setup*, no?
