### ISSUE TITLE
Plugin not using "Firestore INSERT" after waking from background?

### ISSUE THREAD

**Issue by ted-nz** [transistorsoft/react-native-background-geolocation-firebase#15]
Hi Chris,

I have the firebase/firestore adapter enabled and have observed the following:

After extended period of foreground inactivity, if I was to start moving (without opening the app), the location seem to “revert” back into writing to local database instead of firestore.

**In the logs, I see periods of:**
    ✅  INSERT: 8cbc9669-8cb5-43b4-bead-38a13a4b0adb
**Instead of the expected:**
    ✅  Firestore INSERT: 671ec025-093c-4b8c-816b-810d11b2fed0 -> 4QwwFCb1Z3wkqYiqq9VA

Launching the app in the foreground will see the plugin writing into firestore again after sometime, but locations captured during this “window” is lost (at least as far as not being available to firestore).

**I also observed one instance of the following error:**

06-06 08:58:00.130 ERROR [TSFirebaseProxy$3 onFailure]
  ‼️  PERMISSION_DENIED: Missing or insufficient permissions.

Which most of the time is down to security rule violation with firestore. My rules check vehicleId and carrierId supplied via params - which I wouldn’t expect anything to be clearing/resetting i.e.
```
  "params": {
    "vehicleId": "***",
    "carrierId": "***",
    "deviceId": "***"
  }
```
I suspect there is some initialisation / launch sequence that I’m not getting right in all cases, especially if the app ‘wakes up’ from being inactive.
Is there a definitive way to check if the Firebase adapter is “active” at any given point in time? Should I be calling BackgroundGeolocationFirebase.configure({…}) again if I update the main config via BackgroundGeolocation.setConfig({…})?

Logs attached, any help would be appreciated.

[background-geolocatio.log](https://github.com/transistorsoft/react-native-background-geolocation-firebase/files/3259396/background-geolocatio.log)

This log shows two separate periods where it stops writing into Firestore, starting at **06-05 19:07:34.092** and **06-06 08:02:49.566**.

Versions: 

 - react-native-background-geolocation-android **v3.0.5**
 - react-native-background-geolocation-firebase **v0.2.0**

**Comment by christocracy** [comment]
I need your plugin versions:
- `react-native-background-geolocation`
- `react-native-background-geolocation-firebase`

**Comment by ted-nz** [comment]
@christocracy, here you go:

**react-native-background-geolocation-android**@git+ssh://git@github.com:transistorsoft/react-native-background-geolocation-android.git#3.0.5"

**react-native-background-geolocation-firebase**@^0.2.0

**Comment by christocracy** [comment]
Show how you're configuring both plugins.

**Comment by christocracy** [comment]
>Is there a definitive way to check if the Firebase adapter is “active” at any given point in time? 

No.

>Should I be calling BackgroundGeolocationFirebase.configure({…}) again if I update the main config via BackgroundGeolocation.setConfig({…})?

No.

**Comment by christocracy** [comment]
I see the problem:  install `react-native-background-geolocation-android#3.0.6`

**Comment by ted-nz** [comment]
So there was an issue with v3.0.5?
I have updated to v3.0.6, initial testing is looking good. Will do a fair bit more testing in the coming days.

**Comment by christocracy** [comment]
Yes, there was an issue with not registering the firebase adapter in the terminated / Headless state, discovered while integrating the Flutter version of Firebase adapter.
