### ISSUE TITLE
Query: Does it work when app is swapped out from recent apps

### ISSUE THREAD

**Issue by mustaqeem** [transistorsoft/react-native-background-geolocation-firebase#18]
Hi @christocracy,

My question is: does this plugin works when app is swapped our from recent apps on Android?

**Comment by christocracy** [comment]
The firebase adapter for [react-native-background-geolocation](https://github.com/transistorsoft/react-native-background-geolocation) doesn't control this.  `background-geolocation` does, via `stopOnTerminate: false`.  Yes, the firebase adapter will keep receiving locations from `background-geolocation` when the app is terminated.

**Comment by mustaqeem** [comment]
Hey @christocracy,
Can you please help with a sample working example?

**Comment by christocracy** [comment]
react-native-background-geolocation example is clearly linked [in the README](https://github.com/transistorsoft/react-native-background-geolocation#large_blue_diamond-example) over there.

The Firebase adapter example is [in the README](https://github.com/transistorsoft/react-native-background-geolocation-firebase#large_blue_diamond-example) here in this repo.

**Comment by christocracy** [comment]
If this is your first experience with background-geolocation, don’t try and implement this Firebase adapter at the same time.

Just concentrate on react-native-background-geolocation first.  When you’re more comfortable with the main plugin, *then* attempt to implement the Firebase adapter.

**Comment by mustaqeem** [comment]
Does this library need [react-native-firebase](https://invertase.io/oss/react-native-firebase/)?
Will it automatically be installed on installing?

**Comment by christocracy** [comment]
>Does this library need react-native-firebase?

No.

**Comment by mustaqeem** [comment]
then what is firebaseCoreVersion described [here](https://github.com/transistorsoft/react-native-background-geolocation-firebase/blob/master/docs/INSTALL-ANDROID-AUTO.md#open_file_folder-androidbuildgradle)?

**Comment by christocracy** [comment]
They are for the [com.google.firebase](https://github.com/transistorsoft/react-native-background-geolocation-firebase/blob/master/android/build.gradle#L66-L67) dependency versions.

**Comment by mustaqeem** [comment]
Thanks.
I was able to run it.

**Comment by mustaqeem** [comment]
Is it possible to enable authentication at firestore?
Right now, if have no rule set there.

**Comment by christocracy** [comment]
Not currently.
