### ISSUE TITLE
autoSync in .ready() no longer relevant with firebase plugin?

### ISSUE THREAD

**Issue by systemlevel** [transistorsoft/react-native-background-geolocation-firebase#19]
I'm noticing in my case that even when I have` autoSync: false `it will still sync and update to firebase if the device is online.  

Is this expected or is there something wrong with my setup?  

If this is expected does the offline sync "just work" as it normally would with firebase offline sync?

We purchased a license recently and are looking forward to implementing this further.

**Comment by christocracy** [comment]
This isn't an issue with Firebase plugin, it's an issue with react-native-background-geolocation.  Post an issue at the private repo.

**Comment by systemlevel** [comment]
I only have access to a private repo  react-native-background-geolocation-android.  Is that correct or should I have access to another one as well?

**Comment by christocracy** [comment]
`react-native-background-geolocation-android`

**Comment by systemlevel** [comment]
We purchased the react-native-background-geolocation-firebase adaptor as well. Is there a private repo for this that we should be accessing as well?

**Comment by christocracy** [comment]
No private repo here.
