### ISSUE TITLE
Firebase Functions link is missing

### ISSUE THREAD

**Issue by DalerAsrorov** [transistorsoft/react-native-background-geolocation-firebase#2]
The link under *Firebase Functions* in readme is directing to an unknown page. Was there supposed to be more docs on firebase functions?

"You should implement your own *Firebase Functions* (link pointing to unknown page) to "massage" the incoming data in your collection as desired. For example:"

**Comment by christocracy** [comment]
["Firebase Functions"](https://firebase.google.com/docs/functions/)
