### ISSUE TITLE
Question: multiple path

### ISSUE THREAD

**Issue by jorge-uproar** [transistorsoft/react-native-background-geolocation-firebase#20]
I have an app that upload locations to different groups to which a user belong, is there a way to configure multiple paths?

For example a user upload locations to the next groups in realtime:
/group-asd/members/member-1/location
/group-123/members/member-1/location
/group-qwe/members/member-1/location

Do I need a firebase function or is there a direct solution?

**Comment by christocracy** [comment]
You need to handle this at server / Firebase functions.
