### ISSUE TITLE
Property 'timestampsInSnapshotsEnabled' not found on object of type 'FIRFirestoreSettings *'

### ISSUE THREAD

**Issue by BenjaminSAILcloud** [transistorsoft/react-native-background-geolocation-firebase#23]
Hi,

After installing the plugin, I have the following issue on iOS (Android works perfectly fine) : 
```
Property 'timestampsInSnapshotsEnabled' not found on object of type 'FIRFirestoreSettings *'
```

**Comment by christocracy** [comment]
I'll look into it.  It comes [from here](https://github.com/transistorsoft/react-native-background-geolocation-firebase/blob/master/ios/RNBackgroundGeolocationFirebase/RNBackgroundGeolocationFirebase.m#L68)

You can modify the `RNBackgroundGeolocationFirebase.m` file directly by navigating in XCode workspace to:
- `/Pods/DevelopmentPods/RNBackgroundGeolocationFirebase/`

**Comment by BenjaminSAILcloud** [comment]
@christocracy Removing the line with the setting `timestampsInSnapshotsEnabled` was enough to make it work.

```diff

        // TODO make configurable.
        FIRFirestore *db = [FIRFirestore firestore];
        FIRFirestoreSettings *settings = [db settings];
-       settings.timestampsInSnapshotsEnabled = YES;
        [db setSettings:settings];

```

**Comment by christocracy** [comment]
It seems a recent version of the iOS *Firebase* framework has removed this option.

I will wrap that line with property-detection code.

**Comment by BenjaminSAILcloud** [comment]
For those who have the same issue, I added this temporary script to my pipeline in order to have a working CI/CD for my app:

(I am building on a macOS machine)
```bash
sed -i '' '/settings.timestampsInSnapshotsEnabled = YES;/d' node_modules/react-native-background-geolocation-firebase/ios/RNBackgroundGeolocationFirebase/RNBackgroundGeolocationFirebase.m
```
