### ISSUE TITLE
Question : How about the config from BGgeo ?

### ISSUE THREAD

**Issue by BenjaminSAILcloud** [transistorsoft/react-native-background-geolocation-firebase#24]
Hi,

How does this plugin handles the config from the bgGeo plugin, are all the params used ? 
Especially the "HTTP & Persistence Options" part. For exemple if I set the config with `batchSync : true`, will the app sync with the firestore in batches ?  

Thanks.

**Comment by christocracy** [comment]
> if I set the config with batchSync : true, will the app sync with the firestore in batches

No.  Most http/persistence options are ignored when using Firebase adapter.

**Comment by BenjaminSAILcloud** [comment]
Could you provide the config object type actually used by the firebase adapter ?

Does that affect the plugin's methods (e.g. `#getCount`) ?

**Comment by christocracy** [comment]
>Could you provide the config object type actually used by the firebase adapter ?

I don't understand.

>Does that affect the plugin's methods  (e.g. #getCount) ?

When using the Firebase adapter, `BackgroundGeolocation` does not insert locations into its own SQLite database, so `BackgroundGeolocation.getCount()` will *always* return `0`.

**Comment by BenjaminSAILcloud** [comment]
> I don't understand.

Is it possible to have the bg geo plugin's config as following :
<details>
  <summary>Config</summary>

```
    activityRecognitionInterval
    activityType
    allowIdenticalLocations
    authorization
    autoSync
    autoSyncThreshold
    backgroundPermissionRationale
    batchSync
    debug
    deferTime
    desiredAccuracy
    desiredOdometerAccuracy
    disableAutoSyncOnCellular
    disableElasticity
    disableLocationAuthorizationAlert
    disableMotionActivityUpdates
    disableStopDetection
    distanceFilter
    elasticityMultiplier
    enableHeadless
    enableTimestampMeta
    extras
    fastestLocationUpdateInterval
    forceReloadOnBoot
    forceReloadOnGeofence
    forceReloadOnHeartbeat
    forceReloadOnLocationChange
    forceReloadOnMotionChange
    forceReloadOnSchedule
    foregroundService
    geofenceInitialTriggerEntry
    geofenceModeHighAccuracy
    geofenceProximityRadius
    geofenceTemplate
    headers
    heartbeatInterval
    httpRootProperty
    httpTimeout
    isMoving
    locationAuthorizationAlert
    locationAuthorizationRequest
    locationTemplate
    locationTimeout
    locationUpdateInterval
    locationsOrderDirection
    logLevel
    logMaxDays
    maxBatchSize
    maxDaysToPersist
    maxRecordsToPersist
    method
    minimumActivityRecognitionConfidence
    motionTriggerDelay
    notification
    notificationChannelName
    notificationColor
    notificationLargeIcon
    notificationPriority
    notificationSmallIcon
    notificationText
    notificationTitle
    params
    pausesLocationUpdatesAutomatically
    persistMode
    preventSuspend
    reset
    schedule
    scheduleUseAlarmManager
    showsBackgroundLocationIndicator
    speedJumpFilter
    startOnBoot
    stationaryRadius
    stopAfterElapsedMinutes
    stopDetectionDelay
    stopOnStationary
    stopOnTerminate
    stopTimeout
    transistorAuthorizationToken
    triggerActivities
    url
    useSignificantChangesOnly
```
</details> 

But only with the parameters that the firebase adapter actually use (without the params like `url` or `httpTimeout` which the plugin does not use anymore).

> When using the Firebase adapter, BackgroundGeolocation does not insert locations into its own SQLite database, so BackgroundGeolocation.getCount() will always return 0.

Is there a way to access the same informations with the firebase adapter ? 

> No. Most http/persistence options are ignored when using Firebase adapter.

If `maxDaysToPersist` and `maxRecordsToPersist` are ignored, how can I limit the number of documents locally stored on the device in firestore then ? 
In the react native firebase doc, in the settings for firestore section, there is a [`cacheSizeBytes`](https://rnfirebase.io/reference/firestore/settings#cacheSizeBytes) property, could we use it through the plugin's `#ready` config ?

**Comment by christocracy** [comment]
>But only with the parameters that the firebase adapter actually use

Sorry, no.

>Is there a way to access the same informations with the firebase adapter ?

Not currently, no, but it's a very simple plugin for me to modify.  If there's some particular Firebase option you'd like exposed, post a specific issue as a *feature request*.
