### ISSUE TITLE
Could not invoke RNBackgroundGeolocationFirebase.configure

### ISSUE THREAD

**Issue by ssrG12** [transistorsoft/react-native-background-geolocation-firebase#25]
Hi! I have this problem when I run my app.

![WhatsApp Image 2021-02-10 at 19 03 55](https://user-images.githubusercontent.com/51832294/107589188-6fa09b00-6bd3-11eb-9371-184f642e6d15.jpeg)

I think it can be because I haven't de License Key.

**Comment by christocracy** [comment]
Did you *carefully* follow the *Setup Instructions* in the readme?  It looks like you didn't.

**Comment by christocracy** [comment]
Show me your package.json

**Comment by ssrG12** [comment]
> Did you _carefully_ follow the _Setup Instructions_ in the readme? It looks like you didn't.

Yes, I follow the Setup

**Comment by ssrG12** [comment]
> Show me your package.json

```
{
  "name": "tuikit_driver",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "@react-native-community/async-storage": "^1.8.1",
    "@react-native-community/geolocation": "^2.0.2",
    "@react-native-firebase/app": "^10.7.0",
    "@react-native-firebase/firestore": "^10.7.0",
    "axios": "^0.19.2",
    "base-64": "^1.0.0",
    "jetifier": "^1.6.5",
    "moment": "^2.24.0",
    "native-base": "^2.13.12",
    "react": "^16.9.0",
    "react-native": "^0.62.0",
    "react-native-android-location-services-dialog-box": "^2.8.2",
    "react-native-background-geolocation-firebase": "^0.4.0",
    "react-native-extra-dimensions-android": "^1.2.5",
    "react-native-gesture-handler": "^1.6.1",
    "react-native-image-base64": "^0.1.4",
    "react-native-image-picker": "^3.1.3",
    "react-native-keyboard-aware-scrollview": "^2.1.0",
    "react-native-maps": "0.26.1",
    "react-native-maps-directions": "^1.7.6",
    "react-native-modal": "^11.5.6",
    "react-native-onesignal": "^3.6.5",
    "react-native-qrcode-svg": "^6.0.3",
    "react-native-ratings": "^6.5.0",
    "react-native-reanimated": "^1.7.1",
    "react-native-router-flux": "^4.2.0",
    "react-native-screens": "^2.4.0",
    "react-native-sectioned-multi-select": "^0.7.6",
    "react-native-snap-carousel": "^3.8.4",
    "react-native-svg": "^12.1.0",
    "react-native-vector-icons": "^6.6.0",
    "react-native-webview": "^11.2.1",
    "socket.io-client": "^2.3.0"
  },
  "devDependencies": {
    "@babel/core": "^7.6.2",
    "@babel/runtime": "^7.6.2",
    "@react-native-community/eslint-config": "^0.0.5",
    "babel-jest": "^24.9.0",
    "eslint": "^6.4.0",
    "jest": "^24.9.0",
    "metro-react-native-babel-preset": "^0.56.0",
    "react-test-renderer": "16.9.0"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

**Comment by christocracy** [comment]
Just as I thought.  I don't think you understand what this *Firebase Adapter* plugin is.  This is **NOT** a stand-alone location-tracking plugin.  This is merely an *optional* **ADD-ON FOR** [react-native-background-geolocation](https://github.com/transistorsoft/react-native-background-geolocation) that will handle uploading recorded locations *from* `react-native-background-geolocation` to Firebase.

You need to go install `react-native-background-geolocation` *first* (be sure to *carefully* follow *those* Setup steps, they're more complex).

**Comment by christocracy** [comment]
![](https://dl.dropbox.com/s/dl4wndvm0db01by/Screen%20Shot%202021-02-10%20at%207.37.15%20PM.png?dl=1)

**Comment by christocracy** [comment]
So when it comes to purchasing, you must purchase *two* plugins:
1.  `react-native-background-geolocation`:  $349 (*Starter*, 1 key)
2. `react-native-background-geolocation-firebase`: $99 (1 key).

**Comment by ssrG12** [comment]
> So when it comes to purchasing, you must purchase _two_ plugins:
> 
> 1. `react-native-background-geolocation`:  $349 (_Starter_, 1 key)
> 2. `react-native-background-geolocation-firebase`: $99 (1 key).

Okey, now I understand how works the plugins. Thanks!
