### ISSUE TITLE
Property 'timestampsInSnapshotsEnabled' not found on object of type 'FIRFirestoreSettings *'

### ISSUE THREAD

**Issue by jbarlowgd** [transistorsoft/react-native-background-geolocation-firebase#27]
Reviving the issue found here: https://github.com/transistorsoft/react-native-background-geolocation-firebase/issues/23.

After installing the package, linking and trying to run the app, I got the following error.

`Property 'timestampsInSnapshotsEnabled' not found on object of type 'FIRFirestoreSettings *'`

Commenting out the line `settings.timestampsInSnapshotsEnabled = YES;` per the aforementioned thread makes everything run perfectly.

**Comment by christocracy** [comment]
Released to `0.4.1`

**Comment by jbarlowgd** [comment]
Everything looks good now. Thanks!
