### ISSUE TITLE
Geofence is not connected to Firestore

### ISSUE THREAD

**Issue by DalerAsrorov** [transistorsoft/react-native-background-geolocation-firebase#5]
There is `locations` collection that can be seen:
<img width="670" alt="screen shot 2018-09-01 at 5 42 10 am" src="https://user-images.githubusercontent.com/9118852/44946071-cd492000-ada9-11e8-8600-afbee2c42ab5.png">

But when I add a geofence, no geofence collection is added to firestore. It seems like my geofences are still being fetched from and added to the plugin's SQLite store. Here is the code in `componentDidMount`:

```
    BackgroundGeolocationFirebase.configure({
      locationsCollection: "locations",
      geofencesCollection: "geofences"
    }).then(() => {
      console.log('success');
    }).catch((error: Error) => {
      console.log(error);
    });
```

**Comment by christocracy** [comment]
iOS or Android?

**Comment by DalerAsrorov** [comment]
@christocracy iOS!

**Comment by christocracy** [comment]
Found the problem.  `react-native-background-geolocation` was missing a block of code for pushing geofence events to the Firebase plugin.

Install `react-native-background-geolocation` from Github `master`:

```
$ npm install https://github.com/transistorsoft/react-native-background-geolocation.git
```

**Comment by DalerAsrorov** [comment]
Thanks a lot for the fix! Will try it out and let you know how it goes.

**Comment by DalerAsrorov** [comment]
I did `yarn add https://github.com/transistorsoft/react-native-background-geolocation.git` (which is almost same) and also tried removing `node_modules` folder and reinstalling. Still doesn't work. Is there anything else I should do besides `npm install https://github.com/transistorsoft/react-native-background-geolocation.git`?

**Comment by christocracy** [comment]
When you say “doesn’t work”, is there an error?

**Comment by DalerAsrorov** [comment]
What I meant is that, as before, geofences are still not being added to firestore on geofence creation. Also, the app renders the geofences from previous sessions (from plugin's SQLite), which indicates that the proxy's geofencing not hooked up properly for me. Would appreciate any advice!

**Comment by christocracy** [comment]
If it doesn’t work, you haven’t got it installed properly.

What version is installed (from package.json in node_modules)

**Comment by DalerAsrorov** [comment]
In  the app's `package.json` I have:
```
    "react-native-background-geolocation": "git+https://github.com/transistorsoft/react-native-background-geolocation.git",
    "react-native-background-geolocation-firebase": "^0.0.1",
```

In the module's `package.json` I have this:
```
...
  "name": "react-native-background-geolocation",
  "version": "2.13.4",
  "description": "The most sophisticated cross-platform background location-tracking & geofencing module with battery-conscious motion-detection intelligence",  
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "repository": {
    "type": "git",
    "url": "git+ssh://git@github.com/transistorsoft/react-native-background-geolocation.git"
  },
...
```
It doesn't look right indeed. For some reason it points to the next version instead of the github link. Will try something out.

**Comment by christocracy** [comment]
`2.13.4` contains the fix.  In XCode logs after Geofence Event, you will see this:
```
╔═══════════════════════════════════════════════════════════
║ -[TSGeofenceManager fireGeofenceEvent:] 📢ENTER Geofence: test
╚═══════════════════════════════════════════════════════════
✅-[BackgroundTaskManager createBackgroundTask] 2

--> 2018-09-01 23:52:21.672098-0400 FirebaseFoo[47286:8266964] Document added with ID: ORPO5pAYDrDmlCnRhks4 <--
```

**Comment by DalerAsrorov** [comment]
Hi @christocracy ! Thanks for the fast reply and explanation. I ran the app on the actual phone (instead of Simulator) and can see that geofences are being created now! Thanks a lot for your replies and the fix!

**Comment by rlhowell** [comment]
Hi, I'm having this exact problem on Android. Tested on a phone and an emulator. No geofences are created. Locations are updating to Firebase fine but geofences are being retrieved from local storage.  		"react-native-background-geolocation": "^2.13.4",
"react-native-background-geolocation-firebase": "^0.0.1",

**Comment by DalerAsrorov** [comment]
@rlhowell wonder if the android source code still has the same issue
