### ISSUE TITLE
Background (removeGeofence and removeGeofences) do not delete geofences from firstore

### ISSUE THREAD

**Issue by DalerAsrorov** [transistorsoft/react-native-background-geolocation-firebase#6]
Platform: iOS 11.0
```
"react-native-background-geolocation": "https://github.com/transistorsoft/react-native-background-geolocation.git",
"react-native-background-geolocation-firebase": "^0.0.1",
```
Calling `BackgroundGeolocation.removeGeofences()` or `BackgroundGeolocation.removeGeofence(identifier)` does not remove geofence(s) from firestore. Since creation is done synced with firstore, shouldn't deletion also be mirrored in firestore?

**Comment by christocracy** [comment]
No, that’s up to you.  The plugin persists location tracking / geofence *events*..

The scope of the Firestone proxy is going to remain limited.  It will ensure these events are persisted to Firebase, particularly in the case where Android app is terminated with the plugin service operating Headless.

For anything more complex, use react-native-Firebase.

**Comment by DalerAsrorov** [comment]
Thanks for explanation, I will use the `react-native-firebase` library for that. That means that to remove a geofence completely I would have to make 2 calls:

1. Geofence.removeGeofence.
2. Firestore.delete(`geofences/geofenceId`).

Thanks for the proxy!
