### ISSUE TITLE
error running -- clean install

### ISSUE THREAD

**Issue by dturton** [transistorsoft/react-native-background-geolocation-firebase#8]
I am getting this error in the console when trying to run it?? Followed the setup, what can I be missing?

The default Firebase app has not yet been configured. Add `[FIRApp configure];` (`FirebaseApp.configure()` in Swift) to your application initialization.

**Comment by dturton** [comment]
ahh.. I missed adding [FIRApp configure]; to AppDelegate.m. Sorry!

**Comment by christocracy** [comment]
Let me know how it's working for you.

**Comment by TitanKing** [comment]
We use it in our environment for high volume and bg activity tracking. We found it to be working exceptionally well. I want to write some proper help on how exactly we achieved this. By using this plugin with Firebase we found our server API code to be more optimized internally in dealing with a lot of fast locations. Lower battery life and faster delivery to our third party api receivers was achieved. We also found `react-native-background-geolocation-firebase
` plugin to be very stable.
